export const GET_CAFES_FETCH_START = "GET_CAFES_FETCH_START";
export const GET_CAFES_FETCH_SUCCESS = "GET_CAFES_FETCH_SUCCESS";
export const GET_CAFES_FETCH_ERROR = "GET_CAFES_FETCH_ERROR";

export const ADD_CAFE_START = "ADD_CAFE_START";
export const ADD_CAFE_SUCCESS = "ADD_CAFE_SUCCESS";
export const ADD_CAFE_ERROR = "ADD_CAFE_ERROR";

export const UPDATE_CAFE_START = "UPDATE_CAFE_START";
export const UPDATE_CAFE_SUCCESS = "UPDATE_CAFE_SUCCESS";
export const UPDATE_CAFE_ERROR = "UPDATE_CAFE_ERROR";

export const DELETE_CAFE_START = "DELETE_CAFE_START";
export const DELETE_CAFE_SUCCESS = "DELETE_CAFE_SUCCESS";
export const DELETE_CAFE_ERROR = "DELETE_CAFE_ERROR";

export const GET_EMPLOYEES_FETCH_START = "GET_EMPLOYEES_FETCH_START";
export const GET_EMPLOYEES_FETCH_SUCCESS = "GET_EMPLOYEES_FETCH_SUCCESS";
export const GET_EMPLOYEES_FETCH_ERROR = "GET_EMPLOYEES_FETCH_ERROR";

export const ADD_EMPLOYEE_START = "ADD_EMPLOYEE_START";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_ERROR = "ADD_EMPLOYEE_ERROR";

export const UPDATE_EMPLOYEE_START = "UPDATE_EMPLOYEE_START";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_ERROR = "UPDATE_EMPLOYEE_ERROR";

export const DELETE_EMPLOYEE_START = "DELETE_EMPLOYEE_START";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_ERROR = "DELETE_EMPLOYEE_ERROR";
